{{- if .Values.hpa_enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ template "solr.name" . }}"
  labels:
{{ include "solr.common.labels" . | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "solr.fullname" . }}
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}
  metrics:
   - type: Resource
     resource:
       name: cpu
         target:
           type: Utilization
           averageUtilization: {{ .Values.hpa.targetAverageUtilization }}
{{- if .Values.external_metric }}
   - type: External
     external:
       metricName: {{ .Values.external_metrics.metricName }}
       metricSelector:
         matchLabels:
           kube_container_name: {{ .Values.external_metrics.metricSelector }}
       targetAverageValue: {{ .Values.external_metrics.targetAverageValue }}
{{- end }}
{{- end }}
